### ISSUE TITLE
LGPL dependency findbugs:annotations:2.0.0

### ISSUE THREAD

**Issue by rohoet** [eclipse/kuksa.cloud#103]
We found that `findbugs:annotations:2.0.0` is required by `spring-cloud-starter-openfeign:2.1.0` -->  `feign-hystrix:10.1.0` --> `archaius-core:0.6.6`. 

Since `findbugs:annotations:2.0.0` is licensed LGPL, we can either
**a)** define `findbugs:annotations:2.0.0` as being optional, and as a consequence we have to outline which part of the Eclipse Kuksa AppStore is affected by not having `findbugs:annotations:2.0.0` on a machine or
**b)** replace `spring-cloud-starter-openfeign:2.1.0` by another library or a workaround implementation.

This issue has to be covered for a clear Eclipse Kuksa 0.1.0 IP check if the Appstore is intended to be included in that release.

**Comment by rohoet** [comment]
@trademkose Do you have a suggestion for this issue?

**Comment by eriksven** [comment]
see #104

**Comment by rohoet** [comment]
Solved in #104 😀
