### ISSUE TITLE
Add Consent Management to the Appstore

### ISSUE THREAD

**Issue by bs-jokri** [eclipse/kuksa.cloud#113]
As of now the Appstore does not ask the user to give consent to the data that is accessed from a App to be installed. It should be that the appstore request the user to give consent prior installing an app.

Possible approach:

1. A text file with data or functionality of the car used by the app is stored in the app image
2. The text file is evaluated by the app publisher and written into the description field of an artifact in hawkbit
3. The appstore evaluates this description and shows it to the user prior installing an app.

**Comment by trademkose** [comment]
@bs-jokri Hi,
This development has been done. I added an example PERMISSIONFILE.JSON at resourse folder to specify permissions that the car will use. The permisson file's name should be like PERMISSONFILE.JSON and I decided a json format for permission object like this;

 **{
   "name": "CAMERA",
   "type": "CRITICAL",
   "displayName": "Camere permission",
   "description" : "Camere permission description"
 }**
 
We need to upload this file to every single app image. Appstore will read this file before app installation and AppStore will ask this permission to confirm.

**Comment by bs-jokri** [comment]
@trademkose this looks fantastic! Thank you for your efforts. For me this looks like what we need as a first step for the consent management and to demonstrate the overall approach.  One question: What happens if an app does not have a PERMISSIONFILE.JSON? 

@eriksven @phil-hei @rai20 what do you think?

**Comment by trademkose** [comment]
If an app doesn't have a PERMISSIONFILE.JSON, Appstore shows an error message like this, "PERMISSIONFILE.JSON not found or empty." and than you can install the application even if you see this error.

**Comment by bs-jokri** [comment]
@trademkose @phil-hei seems this issue is resolved. Can we close?

**Comment by trademkose** [comment]
@bs-jokri I think. We can close.
