### ISSUE TITLE
Bug: PUT /user/{userId} - UserService

### ISSUE THREAD

**Issue by AssystemCongMinh** [eclipse/kuksa.cloud#13]
The user with the given id will not be updated with the request body because there is a bug in UserService. 

1.) There is no merge with currentUser (user fetched from db) and the parameter userObject (request body).

2.) UserObject (request body) will be saved as new user (see userRepository.save(userObject)).
The newly created user will not have the same id as the given url parameter.

3.) Instead of the currentUser (fetched from db) the user from request body (saved as new user in db) will be returned.

Solution: After validate the userObject (request body) merge the given data to the currentUser (fetched fom db). Then update currentUser ind db and return it from the response.

**Comment by fayvaz** [comment]
Fixed in the last commits.
