### ISSUE TITLE
[Appstore] Dependency injection via Spring Boot

### ISSUE THREAD

**Issue by phil-hei** [eclipse/kuksa.cloud#131]
After some investigations, I see a big problem with the Appstore. Within the appstore, Spring concepts (DI via @Autowired) and JVM managed Objects (via new) are mixed up which lead that DI doesn't work for objets that a created the old fashioned way (cf. https://stackoverflow.com/questions/19896870/why-is-my-spring-autowired-field-null) .Thus, one get a lot of NullPointer.

The only way to solve this in a propper way would be to replace all objects created with new by @Autowired. However, this interference with some UI classes leading to other error messages that are hard to debug for me. So, I'm actually not sure how to continue with that.

**Comment by selobosi** [comment]
Thank you for doing this!

> However, this interference with some UI classes leading to other error messages that are hard to debug for me. So, I'm actually not sure how to continue with that.

If a general solution does not work, let's look at the details! Maybe special cases can be handled in a special way :-). Could you provide the error messages? Are they few so an exhaustive list of error messages and the spots in the code that cause them is possible or are they many so only samples are feasible?

**Comment by phil-hei** [comment]
Created a workaround in https://github.com/eclipse/kuksa.cloud/pull/132 - Basically, I just used DI via the constructor which seems to work now.
However, we should keep in mind that there are potential pitfalls when using DI in other places. So one should be aware that all objects are managed by Spring.
