### ISSUE TITLE
[Appstore] Nullpointer when clicking on install

### ISSUE THREAD

**Issue by phil-hei** [eclipse/kuksa.cloud#135]
When one wants to install a app, a nullpointer exeption may occur. It's probably somehow related to https://github.com/eclipse/kuksa.cloud/issues/131 - I'll investigate.

**Comment by phil-hei** [comment]
I couldn't reproduce the issue with the current version. Can you confirm @trademkose ?

**Comment by trademkose** [comment]
I couldn't reproduce the issue too. There is no problem.
