### ISSUE TITLE
Bug: AppCategoryController - Wrong mapping for path variable

### ISSUE THREAD

**Issue by AssystemCongMinh** [eclipse/kuksa.cloud#16]
Each end point which use @PathVariable are not mapped correctly. 
The name of url path variable used in @DeleteMapping, @GetMapping and @PutMapping should be the same as the parameter of @PathVariable.

Example:
@GetMapping(value = "/appcategories/{**appCategoryId**}")
	public ResponseEntity<?> getAppCategorybyId(@PathVariable String **appCategoryId**)

**Comment by fayvaz** [comment]
Fixed in the last commits.
