### ISSUE TITLE
Bug: POST /app - mandatory fields but not documented 

### ISSUE THREAD

**Issue by AssystemCongMinh** [eclipse/kuksa.cloud#18]
The code indicates that for creating an app object it only requires "name" and "version" in request body but it requires almost every member variable of the app class.

I tried 
{
	"name":"test.create.app",
	"version":"1.0"
}

But worked only with
{
	"name":"test.create.app",
	"version":"1.0", 
	"hawkbitname" : "test.create.app.hawkbit.name",
	"description" : "test.create.app.description",
	"owner" : "test.create.app.owner",
	"publishdate" : 1543245051
}

Please make them either all mandatory or optional.

**Comment by fayvaz** [comment]
Fixed in the last commits.
