### ISSUE TITLE
Bug: POST /app - json property "hawkbitname"

### ISSUE THREAD

**Issue by AssystemCongMinh** [eclipse/kuksa.cloud#19]
Somehow the json property "hawkbitname" can only be at fourth or higher place in the request body.

When I try this
{
	"hawkbitname":"test.app.hawkbit.name",
	"version":"test.app.version",
	"owner":"test.app.owner",
	"name":"test.app.name",
	"description":"test.app.description",
	"publishdate":15432489869
}

I get this
as response
{
    "timestamp": "2018-11-26T16:28:31.355+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: null; nested exception is com.fasterxml.jackson.databind.JsonMappingException: N/A\n at [Source: (PushbackInputStream); line: 2, column: 16] (through reference chain: org.eclipse.kuksa.appstore.model.App[\"hawkbitname\"])",
    "path": "/api/1.0/app"
}

on console
2018-11-26 17:28:31.343  WARN 5760 --- [nio-8082-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: null; nested exception is com.fasterxml.jackson.databind.JsonMappingException: N/A
 at [Source: (PushbackInputStream); line: 2, column: 16] (through reference chain: org.eclipse.kuksa.appstore.model.App["hawkbitname"])

**Comment by AssystemCongMinh** [comment]
I think the bug is in the setHawkbitname(String hawkbitname).

public void setHawkbitname(String hawkbitname) {
		StringBuffer sb = new StringBuffer();
		for (int i = 0; i < name.length(); i++) {
			char c = name.charAt(i);
			if (Character.isWhitespace(c)) {
				c = '_';
			}
			sb.append(c);
		}
		this.hawkbitname = sb.toString();
}

I read that Jackson auto-detect properties from public getter/setter (https://stackoverflow.com/questions/48419419/mapping-json-in-body-to-model-issue-spring-boot?rq=1). That is why it failed when creating an app via api when the name-property is not before the hawkbitname-property.

Please change the setter for hawkbitname to classic setter. 
public void setHawkbitname(String hawkbitname) {
		this.hawkbitname = hawkbitname;
}

If you need extra logic for your Vaadin-Integration, please encapsulate this to some kind of business class.

Btw duplicated code in setHawkbitname. This method already replace whitespaces with '_'.
See: AppEditView.java
line 140: appEditor.app.setHawkbitname(appEditor.app.getName().replace(" ", "_"));
line 160: appEditor.app.setHawkbitname(appEditor.app.getName().replace(" ", "_"));

**Comment by fayvaz** [comment]
Fixed in the last commits.
