### ISSUE TITLE
Bug: GET /apps/user/{userId} - Possibly wrong method

### ISSUE THREAD

**Issue by AssystemCongMinh** [eclipse/kuksa.cloud#20]
Either the documentation or the implementation itself is strange. 

The documetnation says that I get the user's installed apps but the code calls 
appService.findByNameStartsWithIgnoreCaseAndInstalledusersId("", userId, pageable). This method does not return me the desired user's installed apps. Maybe the structure of this query is not right.

There is a method that can be the right query 
findUsersApps(String userId, List<String> oemList, Pageable pageable) but I do not understand the necessary of oemList in this query.

My actions:
1.) Create a user
2.) Create an app category
3.) Create an app
4.) Update app with category
5.) Update user with installed app from 3
6.) Get all installed apps from user from 1

**Comment by AssystemCongMinh** [comment]
I pulled this project and tried to change the implementation. 
I think 
1.) the schema.sql is wrong for the table usersinstalledapps.
There are no status and date.

2.) Update user with installed apps. 
Maybe the ManyToMany annotation has mistakes. When I tried to request this endpoint Jackson recognize my valid jason but the repository cannot saved it correctly (still null).

**Comment by AssystemCongMinh** [comment]
I tired to manually insert the values to the table usersinstalledapps. 
It worked. 
Somehow the user cannot be updated with installes apps.

**Comment by fayvaz** [comment]
Fixed in the last commits.
