### ISSUE TITLE
[Appstore] Appstore should show installed Apps

### ISSUE THREAD

**Issue by rohoet** [eclipse/kuksa.cloud#31]
Currently, it is possible to install the same application multiple times. Users should know whether an app has already been installed on a device.

**Comment by trademkose** [comment]
Hi Robert ,
Could you try again to reproduce this issue via my last commit?
The commit disallow to install the same application multiple times to a device.
But If you get this issue again, Could you provide your steps to reproduce this issue?
Best Regards.

**Comment by m-lenz** [comment]
I dont know @rohoet s setup, but I was not able to reproduce the error.
reinstalling shows:

[![2nd-isntall.png](https://i.postimg.cc/dQH20j4Y/2nd-isntall.png)](https://postimg.cc/BtFLYDrY)

installed apps: 

[![installed.png](https://i.postimg.cc/vHy17PX9/installed.png)](https://postimg.cc/14W5srk5)

**Comment by eriksven** [comment]
@rohoet is the issue still open for you?

**Comment by rohoet** [comment]
Sorry for no updates here and thanks for the reminder.
I think b550779 should have fixed this. Thanks!
