### ISSUE TITLE
Add deployment files for TLS termination via Ambassador gateway

### ISSUE THREAD

**Issue by eriksven** [eclipse/kuksa.cloud#36]

**Comment by selobosi** [comment]
The original title was "enable TLS in Hono MQTT adapter". Hono opens an MQTT port with TLS by default - which uses self-signed certificates.

We also added an ambassador gateway that does TLS termination for all services - I changed the title of this issue to fit for adding this gateway.

**Comment by eriksven** [comment]
see #81
