### ISSUE TITLE
[Appstore] Indexing of database

### ISSUE THREAD

**Issue by alezor** [eclipse/kuksa.cloud#37]
The indexing of the entire database seems to be off.

IDs to Users, Apps, Categories are assigned as follows: 1, 2, 3, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 56 ... 117, 127 etc.
Furthermore, IDs for separate entities (Category, OEMs) are not assigend chronologically for each entity, but are interleaved at the point of creation. e.g:  Category 1, OEM 2

Apart from that, IDs are never reset, or counted down on removal of any entry. Is this the desired behavior or also a bug?

Please have a look into this

**Comment by eriksven** [comment]
Could you specify which database you are referring to?

**Comment by alezor** [comment]
> Could you specify which database you are referring to?

I suppose it is the H2 database, unless i am misinformed. However the problem was visible thanks to the IDs in the Browser UI, so i am just assuming, that those are mapped to the database, since they are created dynamically. I will run a few more tests and see if the problem persists in the newest version

**Comment by selobosi** [comment]
I guess this issue is about the appstore database?

To me, database IDs are an implementation detail and the database is free to choose IDs in the way that suits database operation. The behaviour @alezor described above seems unproblematic to me.

**Comment by alezor** [comment]
![Screenshot 2019-04-25 at 16 02 01](https://user-images.githubusercontent.com/44367008/56743888-bbbcea00-6777-11e9-9783-917624a130f6.png)
Just for clarification: the ID-jumping occurs on restarting the Appstore - as seen in the screenshot (these are e.g. IDs for OEM), I have restarted the Appstore twice, with the ID jumping by 17, and later by 31. If this can be considered neglegible, please close this issue.

**Comment by selobosi** [comment]
Maybe @trademkose can provide some hint on this behaviour. My guess is that the Appstore creates internal objects on startup and uses a global source of IDs.

**Comment by eriksven** [comment]
@trademkose any thoughts on this?

**Comment by trademkose** [comment]
The ID-jumping is negligible. Because of the database is free to choose IDs. So we can close this issue. @eriksven

**Comment by eriksven** [comment]
Thank you for the feedback @trademkose
