### ISSUE TITLE
JDK 9 support

### ISSUE THREAD

**Issue by alezor** [eclipse/kuksa.cloud#38]
Are there plans to support Java versions from 9 upwards in the near future?

**Comment by unly** [comment]
Not sure if there are any plans to migrate to Java 9 at the moment. However, I already thought about having a look into https://openjdk.java.net/projects/jdk/11/. No timeline though

**Comment by selobosi** [comment]
@alezor Are you interested in using a version of Java > 8 in general or would you like use it for a specific part of the system, e.g. the appstore?

**Comment by alezor** [comment]
@selobosi I would like to have a matching Java version for e.g. Hono and Appstore, when run locally (new Hono requires JDK 11)
