### ISSUE TITLE
Distribution version > 50 does not work

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.cloud#44]
The install app does not work if the Distribution version has reached 50.
I think this issue happens because by default the REST call has limit 50.
https://www.eclipse.org/hawkbit/apis/mgmt/distributionsets/

This needs to be changed in the appstore.

**Comment by rai20** [comment]
The install app does not work if the Distribution version has reached 50. 
I think this issue happens because by default the REST call  has limit 50.
https://www.eclipse.org/hawkbit/apis/mgmt/distributionsets/

This needs to be changed in the appstore.

**Comment by trademkose** [comment]
I think we can close this issue too. Because of it was fixed with comment #52 . @rai20 @selobosi

**Comment by eriksven** [comment]
@rai20 @selobosi can we close this issue?

**Comment by rai20** [comment]
This issue is fixed
