### ISSUE TITLE
Automated Checks

### ISSUE THREAD

**Issue by unly** [eclipse/kuksa.cloud#53]
Hi,

currently this repository lacks any automated tests and checks except the contributor agreement with the Eclipse Foundation. Personally, I would prefer to have at least a compile and unit test pipeline to have a quick feedback on a new pull request. There are plenty of free offers like https://travis-ci.org/ and https://circleci.com/ that could be used.

Pipelines are not necessarily limited to compiling. They could also help checking formatting, build images or run integration tests.

For the moment, I would propose to start with a basic job to make sure sources can be compiled in a certain environment.

**Comment by bs-jokri** [comment]
Hi Leon,

Ths is a great idea. Eclipse offers a Jenkins for that purpose (https://jenkins.eclipse.org/kuksa/) and we have already some jobs configured. However the mentioned checks integrated with git are not yet available.
Volunteering to contribute?

Kind regards,
Johannes

Mit freundlichen Grüßen / Best regards

Johannes Kristan
INST-CSS/BSV-OS

Tel. +49 30 726112-432

Von: Leon Graser <notifications@github.com>
Gesendet: Montag, 15. April 2019 17:13
An: eclipse/kuksa.cloud <kuksa.cloud@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [eclipse/kuksa.cloud] Automated Checks (#53)


Hi,

currently this repository lacks any automated tests and checks except the contributor agreement with the Eclipse Foundation. Personally, I would prefer to have at least a compile and unit test pipeline to have a quick feedback on a new pull request. There are plenty of free offers like https://travis-ci.org/ and https://circleci.com/ that could be used.

Pipelines are not necessarily limited to compiling. They could also help checking formatting, build images or run integration tests.

For the moment, I would propose to start with a basic job to make sure sources can be compiled in a certain environment.

**Comment by unly** [comment]
Jenkins could also work. Main point is to have it connected to github and follow the flow. I suppose I need further permissions to operate on that Jenkins server. Can you grant them?

**Comment by eriksven** [comment]
As far as I am concerned, the rights for configuring the Jenkins server are limited to the group of commiters. Currently, there is some ongoing work to configure initial jobs for the Jenkins server.

**Comment by unly** [comment]
closing this issue as needs to be discussed within commiters
