### ISSUE TITLE
[HonoInfluxDBConnector] Support numerical values

### ISSUE THREAD

**Issue by phil-hei** [eclipse/kuksa.cloud#60]
Currently, the HonoInfluxDBConnector stores all incomming values as String: https://github.com/eclipse/kuksa.cloud/blob/dfb25580e4126bbc73cd36cd3a7f2ffad58eb548/utils/hono-influxdb-connector/src/main/java/org/eclipse/kuksa/honoInfluxConnector/InfluxDBClient.java#L83 

This prevents, for example, Grafana to query and visualize such data. Thus, data should be stored according to their incomming data type. As a workaround, I used the following code to store all numercial values as double:

`
for (Map.Entry<String, Object> entry : entries.entrySet()) {
	if (entry.getValue() instanceof Integer || entry.getValue() instanceof Float || entry.getValue() instanceof Double) {
	       pointBuilder.addField(entry.getKey(), ((Number) entry.getValue()).doubleValue());
	} else {
		pointBuilder.addField(entry.getKey(), entry.getValue().toString());
	}
}
`

**Comment by selobosi** [comment]
The change has been deployed. This issue will remain open until the change has been contributed.

**Comment by selobosi** [comment]
The contribution will be based on https://github.com/bsinno/kuksa.cloud/tree/feature/hono-influxdb-connector-update
