### ISSUE TITLE
[HonoInfluxDBConnector] Run it with rover as tenant

### ISSUE THREAD

**Issue by phil-hei** [eclipse/kuksa.cloud#61]
Currently, one instance of the HonoInfluxDBConnector runs and stores all data that goes to the "DEFAULT_TENANT". Due to seperation of concerns and to support the storing of Rover telemetry data, an instance should also be configured and run for the "rover" tenant.

**Comment by selobosi** [comment]
I'll either set up a second HonoInfluxDBConnector or change the implementation to run for multiple tenants.

**Comment by phil-hei** [comment]
Yep, the database basically reflect the tenant and should be the same

**Comment by phil-hei** [comment]
Yep, the database should reflect the tentant, so I would say that both should be the same

**Comment by selobosi** [comment]
The InfluxDB connector has been rewritten and re-deployed for BCX. I'll keep this issue open until the changes have been contributed.

**Comment by selobosi** [comment]
The contribution will be based on https://github.com/bsinno/kuksa.cloud/tree/feature/hono-influxdb-connector-update
