### ISSUE TITLE
[Appstore] Configuration should permit HTTPS connections to hawkBit

### ISSUE THREAD

**Issue by selobosi** [eclipse/kuksa.cloud#65]
We use a hawkbit deployment that is secured using TLS so clients shall use HTTPS to connect to it. Currently the appstore uses `hawkbit.host` and `hawkbit.port` to configure a plain HTTP connection and the schema `http://` is constant in the sources.

The sources, property files and documentation need to be updated to be able to use `hawkbit.url` (that's just a suggestion but the most meaningful one that came to my mind) instead of `hawkbit.host` and `hawkbit.port` to configure e.g. `http://myHawkbitHost:8443`.

This issue resulted from #63 . @trademkose could you work on this?

**Comment by trademkose** [comment]
Okay. I will do it as soon as possible.
I am going to use _hawkbit.url_ instead of _hawkbit.host_ and _hawkbit.port_ for hawkbit configuration.
