### ISSUE TITLE
Deploy Traccar Server on the Cloud Platform

### ISSUE THREAD

**Issue by rai20** [eclipse/kuksa.cloud#67]
Need to find a way to deploy Traccar server on the kuksa-cloud instance for gathering GPS data from kuksa dongle.

Traccar Server = https://www.traccar.org/server/ 

There are a few instances of it in the public cloud but would be great to have one only for kuksa.

**Comment by selobosi** [comment]
Releases are available from https://github.com/traccar/traccar

**Comment by selobosi** [comment]
Traccar server is deployed in the cloud. No persistence is configured yet. This issue remains open until the deployment (with persistence) is contributed.

**Comment by selobosi** [comment]
The initial deployment will be without persistence, see #84 for adding persistence.

**Comment by eriksven** [comment]
eclipse#67 seems to resolve this issue
