### ISSUE TITLE
[Appstore] Feature Request: Advanced API for testing

### ISSUE THREAD

**Issue by m-lenz** [eclipse/kuksa.cloud#69]
atm. we are testing the process of `buying` and `installing` manually.
Is it possible to expose those actions on the API? 
This would allow us to automate those tests and give more detailed feed-back on possible issues.

**Comment by selobosi** [comment]
@trademkose what do you think of this feature?

**Comment by trademkose** [comment]
@selobosi I can do this feature as soon as possible. Also I am going to update Swagger Api  Documentation after the developing.
Process of buying and installing an application will be added to api.

**Comment by trademkose** [comment]
Hi All,
I have developmented this feature with commit #71  .
You can use api following paths to purchase, install, uninstall;

1- @PostMapping(value = "/app/{appId}/purchase/{userId}")	
2- @PostMapping(value = "/app/{appId}/install/{userId}") --Device name should be given in Request Body as String
3- @DeleteMapping(value = "/app/{appId}/uninstall/{userId}") --Device name should be given in Request Body as String
An example url : http://localhost:8082/api/1.0/app/34/uninstall/1
