### ISSUE TITLE
add more information to pom.xml of the app-store

### ISSUE THREAD

**Issue by eriksven** [eclipse/kuksa.cloud#72]
We need to adapt the pom.xml of the app store a bit by adding the license (<license>) and a link to the website of Eclipse Kuksa (<site>). 
Automatic code analysis tools (e.g. ORT https://github.com/heremaps/oss-review-toolkit) may use the information from the parent pom.xml are. In the case of the app-store this is the information for the spring-boot-starter-parent which has another license (Apache 2.0) and obviously another website.

**Comment by eriksven** [comment]
see #76

**Comment by trademkose** [comment]
#76 was merged. Can we close this issue? @eriksven

**Comment by eriksven** [comment]
Thank you for raising this. Yes we can close this issue.
