### ISSUE TITLE
[Appstore] ignores hawkbit.username and hawkbit.password

### ISSUE THREAD

**Issue by selobosi** [eclipse/kuksa.cloud#73]
While Appstore [README.md](https://github.com/eclipse/kuksa.cloud/blob/master/kuksa-appstore/readMe.md) states that `hawkbit.username` and `hawkbit.password` can be configured, [HawkbitFeignConfig](https://github.com/eclipse/kuksa.cloud/blob/b550779c83dd3d1a26c9eb024031cda7c8e2c73d/kuksa-appstore/src/main/java/org/eclipse/kuksa/appstore/configuration/HawkbitFeignConfig.java) uses hard-coded values instead.

@trademkose, could you fix that? Thank you!

**Comment by trademkose** [comment]
@selobosi I have a pull request that will solve this issue. The Pull Request is #74
