### ISSUE TITLE
Hawkbit -> Appstore Delete Sync Issue

### ISSUE THREAD

**Issue by alezor** [eclipse/kuksa.cloud#77]
When deleting a Software Distribution in Hawkbit, it's previously app in the Appstore remains in the database, and is even visible. However it can not be removed, even if chaning the Appname - neither can the Category of this app be removed. This naturally prevents the reusing of the Appname, even though there is no such functioning app with this Appname in Hawkbit.

Error: Software Module not found on Hawkbit

**Comment by trademkose** [comment]
When we were developing Appstore, we have supposed that It is prohibited to delete an application on Hawkbit. If you want to delete an application, you should delete the app from appstore. Appstore deletes the application that you want to delete from own database and the hawkbit instance too.
So You shouldn't delete application on hawkbit. Hawkbit is a backend application for us.

**Comment by alezor** [comment]
Sounds perfectly reasonable. However, now that the case has happened anyway, is there any possibility to deal with the undeletable App and its Category in the Azure Appstore right now, apart from scrapping it and setting it up again?
